### ISSUE TITLE
Secondary MP Tool: Fail: Not ISP mode?

### ISSUE THREAD

**Issue by alcohime** [ArcadeHustle/RingEdge_SSD_Softmod#7]
Trying to provision a Transcend SSD370S (64gb).

First issue was the drive did not show up. Turns out this tool only looks over USB and not SATA, and also doesn't like my Sabrent SATA->USB station. Switched over to a Kingwin SATA->USB and the drive now shows up.

Hitting Start throws back an error that the drive isn't in ISP mode, and everything remains unchanged. Some reading tells me that ISP mode/ROM mode/test mode/programmer mode is initiated as a fallback when a drive fails, but drives can be forced into it if a  specific pin is shorted when the drive is connected to PC.

I've tried jumping every through-hole to ground and tried jumping every pair of through-holes, but no luck. Seeking advice.

![Untitled](https://user-images.githubusercontent.com/54160112/91826921-0f083d80-ebf3-11ea-9d29-0747d4925bce.png)

![IMG_20200901_012719251](https://user-images.githubusercontent.com/54160112/91826945-17f90f00-ebf3-11ea-9519-f63f90b8155b.jpg)

![IMG_20200901_012739809](https://user-images.githubusercontent.com/54160112/91826948-1891a580-ebf3-11ea-8bd2-cf4478468b31.jpg)

**Comment by alcohime** [comment]
Hello,

Was hardware issue on my end - switched to an old laptop running Win7 Ultimate and it worked.

![image](https://user-images.githubusercontent.com/54160112/95004882-f00c1b00-05a5-11eb-9e71-19d412867a00.png)

Bridge these two points to put the drive in ISP mode (this was still needed)

**Comment by MAVProxyUser** [comment]
Great tip on the ISP mode.

**Comment by ArcadeHustle** [comment]
Great tip on the ISP mode.
